name: Flutter CI-CD

# 1
on:
  # 2
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v4
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      # 10   
      - uses: subosito/flutter-action@v2

      # 12
      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Run Dart Formatter
        run: dart format --set-exit-if-changed .

      - name: Run Unit Tests
        run: flutter test

      # Runs a set of commands using the runners shell
      - name: Build APK
        run: flutter build apk

      # Upload generated apk to the artifacts.
      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: debug-apk
      #    path: build/app/outputs/apk/debug/app-debug.apk

      # Create tag
      - uses: actions/checkout@v4
      - uses: jacopocarlini/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # Build APK and create GitHub release
      - name: Build APK and create GitHub release
        uses: Dank-del/flutter-build-and-publish-action@v1
            
