name: Flutter CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version de release (spécifier une version pour créer une release. Laisser vide pour un build de debug)'
        required: false
        default: ''

jobs:
  # JOB : Mise à jour de la version dans le pubspec.yaml
  update-version:
    name: "Update Version"
    runs-on: ubuntu-latest
    if: github.event.inputs.releaseVersion
    outputs:
      new-version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Update version in pubspec.yaml
        id: set-version
        run: |
          new_version="version: ${{ github.event.inputs.releaseVersion }}+${GITHUB_RUN_NUMBER}"
          echo "Setting new version in pubspec.yaml: $new_version"
          sed -i "s/version: .*/$new_version/" pubspec.yaml
          echo "version=$new_version" >> $GITHUB_OUTPUT 

  # JOB : Build Android ou Build iOS
  build:
    needs: update-version
    if: always()  # Garantit que ce job s'exécute même si update-version est skipped
    name: ${{ matrix.name }}  # Définit le nom du job en fonction de la matrice ("Build Android" ou "Build iOS")
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: android
            build-command: apk
            name: "Build Android"
          - os: macos-latest
            platform: ios
            build-command: ios --no-codesign
            name: "Build iOS"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      # Mis en cache des dépendances de Gradle (accélére la construction des builds Android)
      - name: Setup Java with Gradle cache (only for Android)
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Run Dart Formatter
        run: dart format .

      - name: Run Unit Tests
        run: flutter test

      - name: Build ${{ matrix.platform }} App
        run: |
          if [[ -z "${{ github.event.inputs.releaseVersion }}" ]]; then
            echo "Building debug ${{ matrix.platform }} app..."
            flutter build ${{ matrix.build-command }} --debug
          else
            echo "Building release ${{ matrix.platform }} app..."
            flutter build ${{ matrix.build-command }} --release
          fi

      - name: List Build Outputs
        run: |
          if [ "${{ matrix.platform }}" = "android" ]; then
            ls -l build/app/outputs/flutter-apk/
          else
            ls -l build/ios/iphoneos/
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ github.event.inputs.releaseVersion || 'debug' }}
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/ios/iphoneos/*.app

  # JOB : Création de la release
  create_release:
    name: "Create Release"
    runs-on: ubuntu-latest
    needs: [build] # S'exécute après le job 'build'
    if: ${{ github.event.inputs.releaseVersion != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses:  softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981 # Commit SHA
        with:
          tag_name: ${{ github.event.inputs.releaseVersion }}
          name: Release ${{ github.event.inputs.releaseVersion }}
          body: Description of the changes for this release...
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
