name: Flutter CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version (specify version to create a release, leave blank for debug build)'
        required: false
        default: ''

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Run Dart Formatter
        run: dart format .

      - name: Run Unit Tests
        run: flutter test

      - name: Build APK
        run: |
          if [[ -z "${{ github.event.inputs.releaseVersion }}" ]]; then
            echo "Building debug APK..."
            flutter build apk --debug
          else
            echo "Building release APK..."
            flutter build apk --release
          fi

      - name: List APK files
        run: ls -l build/app/outputs/flutter-apk/

      - uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.event.inputs.releaseVersion || 'debug' }}
          path: build/app/outputs/flutter-apk/*.apk

  build-ios:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Run Dart Formatter
        run: dart format .

      - name: Run Unit Tests
        run: flutter test

      - name: Build iOS
        run: |
          if [[ -z "${{ github.event.inputs.releaseVersion }}" ]]; then
            echo "Building debug iOS app..."
            flutter build ios --debug --no-codesign
          else
            echo "Building release iOS app..."
            flutter build ios --release --no-codesign
          fi

      - name: List Build Outputs
        run: ls -l build/ios/iphoneos/

      - uses: actions/upload-artifact@v4
        with:
          name: ipa-${{ github.event.inputs.releaseVersion || 'debug' }}
          path: /Users/runner/work/Flutter_CI-CD/Flutter_CI-CD/build/ios/iphoneos/*.app

  create_release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    if: ${{ github.event.inputs.releaseVersion != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.releaseVersion }}
          release_name: Release ${{ github.event.inputs.releaseVersion }}
          body: "Description of the changes for this release"
          draft: false
          prerelease: false
